/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ddd.services;

import base.exception.BusinessRuntimeException;
import ddd.api.UserRepository;
import ddd.auth.AuthenticationService;
import ddd.auth.model.user.User;
import ddd.code.AppExceptionCodeEnum;
import ddd.usecase.LoginUseCase;
import ddd.usecase.ShowPersonalInfoUseCase;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * 首页
 *
 * @author wulei
 */
@Component
@Slf4j
@Setter(onMethod = @__(@Autowired))
public class WelcomeAppService {

    private UserRepository userRepository;
    private AuthenticationService authenticationService;

    /**
     * 登录
     *
     * @param loginRequest 请求参数
     * @return
     */
    public String login(LoginUseCase.Request loginRequest) {
        return authenticationService.authenticate(loginRequest.getUserName(), loginRequest.getPassword());
    }

    /**
     * 展示个人信息
     *
     * @param request 请求参数
     */
    public ShowPersonalInfoUseCase.Response showPersonalInfo(ShowPersonalInfoUseCase.Request request) {

        Long userId = request.getUserId();
        User userInfo = userRepository.getUserById(userId);

        if (userInfo==null) {
            throw new BusinessRuntimeException(AppExceptionCodeEnum.USER_NOT_FOUND);
        }

        ShowPersonalInfoUseCase.Response resp = new ShowPersonalInfoUseCase.Response();
        resp.setUserName(userInfo.getUserName());
        resp.setUserId(userInfo.getUserId().id());
        return resp;
    }
}
