spring:
  datasource:
    # http://localhost:8080/h2-console/
    # url: jdbc:h2:mem:testdb
    # h2的文件创建在家目录
    # url: jdbc:h2:file:~/data/DDDemo.db

    url: jdbc:h2:file:~/data/DDDemo1.db
    driver-class-name: org.h2.Driver
    # 无需用户名
    username: sa
    # 无需密码
    password: password

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        # 开启缓存
        cache:
          use_second_level_cache: false
          use_query_cache: false
          # 缓存的实体类
          cache_shared_private_ownership: true
          # 缓存的实体类
          cacheable_entities: com.dd.demo.entity.*
  # 开启事务
debug: false
