/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ddd.auth.services;

import ddd.common.AppResponseDTO;
import ddd.auth.usecase.LoginUseCase;
import ddd.auth.usecase.ShowPersonalInfoUseCase;
import org.springframework.stereotype.Component;

/**
 * 首页
 *
 * @author wulei
 */
@Component
public class WelcomeAppService {

    /**
     * 登录
     * @param loginRequest 请求参数
     */
    public AppResponseDTO<Void> login(LoginUseCase.Request loginRequest) {

        System.out.println("login " + loginRequest.getUserName() + "##" + loginRequest.getPassword());

        return AppResponseDTO.ok();
    }

    /**
     * 展示个人信息
     * @param request 请求参数
     */
    public AppResponseDTO<ShowPersonalInfoUseCase.Response> showPersonalInfo(ShowPersonalInfoUseCase.Request request) {
//        ShowPersonalInfoUseCase showPersonalInfoUseCase = new ShowPersonalInfoUseCase();
//        System.out.println("login " + loginRequest.getUserName() + "##" + loginRequest.getPassword());

        return AppResponseDTO.ok();
    }
}
