/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("ScaffoldingDDD.java-library-conventions")
    alias(libs.plugins.springBoot)
}
apply(plugin = "io.spring.dependency-management")
dependencies {
    implementation(project(":common"))
    implementation("org.springframework:spring-context")
}


