/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("ScaffoldingDDD.java-library-conventions")
    id("org.springframework.boot") version "3.2.0"
    id("io.spring.dependency-management") version "1.1.4"
}

dependencies {
    implementation(project(":common"))
    implementation(project(":domain"))
    implementation("org.springframework:spring-context")
}

//application {
//    // Define the main class for the application.
//    mainClass.set("ScaffoldingDDD.app.App")
//}
