/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("spirng6.ddd.java-library-conventions")
}

//application {
//    // Define the main class for the application.
//    mainClass.set("spirng6.ddd.app.App")
//}
