/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("ScaffoldingDDD.java-library-conventions")
}

//application {
//    // Define the main class for the application.
//    mainClass.set("ScaffoldingDDD.app.App")
//}
