/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("spirng6.ddd.java-library-conventions")
    id("org.springframework.boot") version "3.2.0"
    id("io.spring.dependency-management") version "1.1.4"
}

dependencies {
    implementation(project(":domain"))
    implementation(project(":app"))
    implementation("org.springframework.boot:spring-boot-starter-web")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
//    implementation("io.r2dbc:r2dbc-spi:0.8.4.RELEASE")


}
