/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("ScaffoldingDDD.java-common-conventions")
    alias(libs.plugins.springBoot)
    alias(libs.plugins.springDependencyManagement)
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
}

//application {
//    // Define the main class for the application.
//    mainClass.set("ScaffoldingDDD.app.App")
//}
