/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("ScaffoldingDDD.java-library-conventions")
    alias(libs.plugins.springBoot)
}
apply(plugin = "io.spring.dependency-management")
dependencies {
    implementation(project(":app"))
    implementation(project(":common"))
    implementation("org.springframework:spring-context")
    implementation("org.springframework:spring-webmvc")
}

//application {
//    // Define the main class for the application.
//    mainClass.set("ScaffoldingDDD.app.App")
//}
